cluster_name: local-cluster

provider:
  type: local
  head_ip: localhost
  worker_ips: [] # For local provider, this is usually empty or not needed

auth:
  ssh_user: matthieuneau # Make sure this user can SSH to localhost without a password if needed, though often not required for 'local' provider

# Running Ray in Docker images is optional
docker:
  image: "rayproject/ray:latest"
  container_name: "ray_container"
  # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
  # if no cached version is present.
  pull_before_run: True
  run_options: # Extra options to pass into "docker run"
    - --ulimit nofile=65536:65536
    - -p
    - "8000:8000"
    - -p
    - "6379:6379"
    - -p 
    - "8265:8265"

# The minimum number of workers nodes to launch (0 for local head-only)
min_workers: 0

# The maximum number of workers nodes to launch (0 for local head-only)
max_workers: 0

# Commands to start ray on the head node *inside the container*
head_start_ray_commands:
  - ray stop || true
  - ray start --head --port=6379  --dashboard-host=0.0.0.0

# It's good practice to include setup commands if needed, though maybe not for this basic setup
# setup_commands:
#   - # e.g., pip install my_dependency

# Commands to run on the head node *before* Ray starts
# head_setup_commands:
#  - # Commands to run on the head node before starting Ray

# Commands to run on worker nodes *before* Ray starts (not applicable here as workers=0)
# worker_setup_commands:
#   - # Commands to run on worker nodes before starting Ray

# Commands to start ray on worker nodes (not applicable here as workers=0)
# worker_start_ray_commands:
#   - ray stop || true
#   - ray start --address=$RAY_HEAD_IP:6379 --object-store-memory=...